### ISSUE TITLE
Upload new release

### ISSUE THREAD

**Issue by Leystryku** [danielga/gm_filesystem#3]
Hey,
could you update a new release (especially for linux)?

Thanks.

**Comment by danielga** [comment]
Try [these builds](https://github.com/danielga/gm_filesystem/releases/tag/v2) please.

**Comment by Leystryku** [comment]
Hey,
I've tried them and and am encountering the same issue
![](https://i.imgur.com/KRlWXaU.png)


If it helps, it's the normal 32 bit srcds on ubuntu LTS

**Comment by danielga** [comment]
I've made some fixes to `garrysmod_common` and this module, try [these new builds](https://github.com/danielga/gm_filesystem/releases/tag/1.4.2) please.

**Comment by Leystryku** [comment]
The good thing is it compiles now and requires successfully.

The bad news is, for whatever reason now the filesystem table does not get added to _G, so none of the functions are callable.

**Comment by Leystryku** [comment]
Alright, nevermind my last post.
It's working fine now.

Thank you @danielga :)
